services:
  app:
    image: public.ecr.aws/w9f8p7q3/machine-learning:latest  # Especifica a imagem do ECR
    volumes:
      - ../src:/app/src
      - ../data:/app/data
    ports:
      - "8000:8000"  # Porta exposta para acessar a aplicação
    environment:
      - ENV=development  # Variável de ambiente para diferenciar ambientes
    command: ["python", "/app/src/main.py"]  # Caminho correto para o main.py