name: CI/CD Pipeline with ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar AWS CLI e Docker
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
        docker --version

    - name: Fazer login no ECR
      env:
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin 863518425456.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build da imagem
      run: |
        GIT_SHA=$(git rev-parse --short HEAD)
        docker build -t machine-learning:$GIT_SHA .
        docker tag machine-learning:$GIT_SHA 863518425456.dkr.ecr.us-east-1.amazonaws.com/machine-learning:$GIT_SHA
        docker tag machine-learning:$GIT_SHA 863518425456.dkr.ecr.us-east-1.amazonaws.com/machine-learning:latest

    - name: Push da imagem para o ECR
      run: |
        docker push 863518425456.dkr.ecr.$AWS_REGION.amazonaws.com/machine-learning:$GIT_SHA
        docker push 863518425456.dkr.ecr.$AWS_REGION.amazonaws.com/machine-learning:latest
