name: CI/CD Pipeline with Public ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar AWS CLI e Docker
      run: |
        if ! aws --version; then
          echo "AWS CLI não encontrado. Instalando..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        fi
        aws --version
        docker --version

    - name: Fazer login no ECR Público
      env:
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr-public get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin public.ecr.aws

    - name: Build da imagem
      run: |
        GIT_SHA=$(git rev-parse --short HEAD)
        docker build -t machine-learning:$GIT_SHA ./docker
        docker tag machine-learning:$GIT_SHA public.ecr.aws/w9f8p7q3/machine-learning:$GIT_SHA
        docker tag machine-learning:$GIT_SHA public.ecr.aws/w9f8p7q3/machine-learning:latest

    - name: Push da imagem para o ECR Público
      run: |
        docker push public.ecr.aws/w9f8p7q3/machine-learning:$GIT_SHA
        docker push public.ecr.aws/w9f8p7q3/machine-learning:latest
